apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-apps
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: nginx-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-apps
spec:
  selector:
    app: nginx
  ports:
    - port: 80
