# values.yaml
adminUser: admin
adminPassword: P@ssw0rd

persistence:
  enabled: true
  size: 1Gi
  # storageClassName: gp3

service:
  type: NodePort
  port: 80

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-gateway.logs.svc
    - name: Tempo
      type: tempo
      url: http://tempo.tracing.svc:3100
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.metrics.svc
      isDefault: true