apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/nginx

namePrefix:
  local-cluster-1-

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: nginx
    patch: |-
      # Cluster specific config path
      - op: replace
        path: /spec/sources/1/path
        value: argocd/prod/local-cluster-1/nginx/config