# Pod to run a simple loki query to test the loki setup
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-sample-logs
  namespace: logs
spec:
  template:
    spec:
      containers:
      - name: loki-test
        image: quay.io/curl/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          curl -H "Content-Type: application/json" -XPOST -s "http://loki-gateway.logs.svc.cluster.local/loki/api/v1/push"  --data-raw "{\"streams\": [{\"stream\": {\"job\": \"loki-test\"}, \"values\": [[\"$(date +%s)000000000\", \"Stream sent to Loki successfully\"]]}]}"
      restartPolicy: Never