# This is a simple job that sends traces to the OTEL Collector once.
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-sample-traces
  namespace: tracing
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: traces
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.96.0
        args:
          - traces
          - --otlp-insecure
          - --rate
          - "20"
          - --duration
          - 5s
          - --otlp-endpoint
          - opentelemetry-collector.tracing.svc:4317
      restartPolicy: Never