role: Agent
service:
  enabled: false
logLevel: error
tolerations:
  - operator: Exists
podMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
# https://vector.dev/docs/reference/configuration/
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: false
  sources:
    vector_metrics:
      type: internal_metrics
      scrape_interval_secs: 30
    kubernetes_logs:
      type: kubernetes_logs
      # Supressing keys from output
      pod_annotation_fields:
          container_id: ""
          pod_labels: ""
          pod_annotations: ""
          pod_uid: ""
          pod_node_name: ""
          pod_owner: ""
          pod_ips: ""
      node_annotation_fields:
          node_labels: ""
      namespace_annotation_fields:
          namespace_labels: ""
      exclude_paths_glob_patterns:
      - "**/kube-system*/**"

  sinks:
    prom-exporter:
      type: prometheus_exporter
      inputs:
        - vector_metrics
      address: 0.0.0.0:9598
    loki:
      type: loki
      inputs:
        - kubernetes_logs
      endpoint: http://loki-gateway.logs.svc
      encoding:
        codec: json
      compression: gzip
      # Ensure the batch size of the Vector Loki sink is less than the Loki server grpc_server_max_recv_msg_size
      # https://vector.dev/docs/reference/configuration/sinks/loki/#batch.max_bytes
      # https://grafana.com/docs/loki/latest/configure/#server
      batch:
        max_bytes: 200000
      out_of_order_action: accept
      labels:
        env: dev
        namespace: |-
          {{ print "{{ kubernetes.pod_namespace }}" }}
        container: |-
          {{ print "{{ kubernetes.container_name }}" }}
        pod: |-
          {{ print "{{ kubernetes.pod_name }}" }}
        event: |-
          {{ print "{{ source_type }}" }}