apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/argocd

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: argocd
    patch: |-
      # project name
      - op: replace
        path: /spec/project
        value: local-cluster-1-cluster-apps

      # Cluster specific config path
      - op: replace
        path: /spec/sources/1/path
        value: argocd/prod/local-cluster-1/argocd/config