apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  description: Manages all cluster related resources

  destinations:
  - namespace: '*'
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  sourceRepos:
  - https://github.com/joelp172/k8s-tools.git
  - https://zapier.github.io/kubechecks/
  - https://stakater.github.io/stakater-charts
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability-apps
  namespace: argocd
spec:
  description: Manages all observability related resources

  destinations:
  - namespace: '*'
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  sourceRepos:
  - https://github.com/joelp172/k8s-tools.git
  - https://grafana.github.io/helm-charts
  - https://prometheus-community.github.io/helm-charts
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-apps
  namespace: argocd
spec:
  description: Manages all test applications

  destinations:
  - namespace: '*'
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  sourceRepos:
  - https://github.com/joelp172/k8s-tools.git