apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/reloader

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: reloader
    patch: |-
      # Helm values override
      - op: add
        path: /spec/sources/1/helm/valueFiles/-
        value:
          $values/argocd/prod/local-cluster-1/reloader/reloader-values.yaml