apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/bitwarden

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: bitwarden
    patch: |-
      # project name
      - op: replace
        path: /spec/project
        value: local-cluster-1-cluster-apps

      # Helm values override
      - op: add
        path: /spec/sources/1/helm/valueFiles/-
        value:
          $values/prod/local-cluster-1/bitwarden/bitwarden-values.yaml
