apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: cloudflare-api-token
  namespace: nginx
spec:
  organizationId: "fbc90c4c-b532-48eb-9b3a-b20f014ada21"
  secretName: tunnel-credentials
  map:
    - bwSecretId: 4c0c11e6-fa18-4fe2-8a55-b20f014e5b25
      secretKeyName: credentials.json
  authToken:
    secretName: bw-auth-token
    secretKey: token