# https://github.com/grafana/helm-charts/blob/main/charts/tempo/values.yaml
# https://grafana.com/docs/tempo/latest/configuration/#configure-tempo

replicas: 1

persistence:
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus

tempo:
  ingester:
    flush_all_on_shutdown: true
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1

  retention: 720h

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

  compactor:
    compaction:
      block_retention: 72h

  global_overrides:
    # Override trace size limit to 10MB
    max_bytes_per_trace: 10000000

  # server:
    # log_level: error

  config:
    frontend:
      address: 0.0.0.0
      compress_responses: true