# https://github.com/grafana/helm-charts/tree/main/charts/grafana
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: nginx
  namespace: argocd
spec:
  project: test-apps
  sources:
    - repoURL: https://github.com/joelp172/k8s-tools.git
      targetRevision: HEAD
      path: argocd/base/nginx/config

    # Cluster specific extras
    - repoURL: https://github.com/joelp172/k8s-tools.git
      targetRevision: HEAD
      path: ""

  destination:
    namespace: nginx
    name: in-cluster

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true