# https://github.com/grafana/helm-charts/tree/main/charts/grafana
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: argocd
  namespace: argocd
spec:
  project: cluster-apps
  sources:
    # Give the Helm release access to a values file so we don't have to inline
    - repoURL: https://github.com/joelp172/k8s-tools.git
      targetRevision: HEAD
      path: argocd/cluster-apps/argocd

    # Extra config
    - repoURL: https://github.com/joelp172/k8s-tools.git
      targetRevision: HEAD
      path: ""

  destination:
    namespace: argocd
    name: in-cluster

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true